import { execSync } from "child_process";
import {
  SlackBugReport,
  GeminiFixProposal,
  VerificationResult,
  PullRequestResult,
} from "./types";

export class GitPrManager {
  private workspaceRoot: string;
  private githubToken: string;
  private repoOwner: string;
  private repoName: string;

  constructor(workspaceRoot: string = process.cwd()) {
    this.workspaceRoot = workspaceRoot;
    this.githubToken =
      process.env.GITHUB_TOKEN || process.env.GH_TOKEN || "";

    // Parse origin remote
    const remoteUrl = this.getRemoteUrl();
    const parsed = this.parseRepoSlug(remoteUrl);
    this.repoOwner = parsed.owner;
    this.repoName = parsed.repo;
  }

  private getRemoteUrl(): string {
    try {
      return execSync("git config --get remote.origin.url", {
        cwd: this.workspaceRoot,
        encoding: "utf-8",
      }).trim();
    } catch {
      return "https://github.com/ttekit/explys.git";
    }
  }

  private parseRepoSlug(url: string): { owner: string; repo: string } {
    const match = url.match(/[:/]([^/]+)\/([^/]+?)(?:\.git)?$/);
    if (match) {
      return { owner: match[1], repo: match[2] };
    }
    return { owner: "ttekit", repo: "explys" };
  }

  public getCurrentBranch(): string {
    try {
      return execSync("git branch --show-current", {
        cwd: this.workspaceRoot,
        encoding: "utf-8",
      }).trim();
    } catch {
      return "product";
    }
  }

  /**
   * Creates a dedicated fix branch
   */
  public createBranch(bugTitle: string, baseBranch?: string): string {
    const resolvedBase = baseBranch || this.getCurrentBranch();
    const slug = bugTitle
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .slice(0, 30)
      .replace(/^-|-$/g, "");
    const timestamp = Math.floor(Date.now() / 1000);
    const branchName = `fix/qa-slack-${timestamp}-${slug || "bugfix"}`;

    execSync(`git checkout -b ${branchName}`, {
      cwd: this.workspaceRoot,
      stdio: ["ignore", "pipe", "pipe"],
    });

    console.log(`Created and switched to fix branch: ${branchName} (based on ${resolvedBase})`);
    return branchName;
  }

  /**
   * Commits and pushes changes
   */
  public commitAndPush(
    branchName: string,
    proposal: GeminiFixProposal,
    reporter: string,
    dryRun: boolean = false
  ): void {
    if (dryRun) {
      console.log(`[DRY RUN] Would commit and push to branch: ${branchName}`);
      return;
    }

    const commitMsg = `fix(qa): ${proposal.bugSummary}\n\nReported by Slack QA: @${reporter}\nAutomated fix generated via Gemini & Graphify`;

    execSync("git add -A", { cwd: this.workspaceRoot });
    execSync(`git commit -m "${commitMsg.replace(/"/g, '\\"')}"`, {
      cwd: this.workspaceRoot,
      stdio: ["ignore", "pipe", "pipe"],
    });

    execSync(`git push -u origin ${branchName}`, {
      cwd: this.workspaceRoot,
      stdio: ["ignore", "pipe", "pipe"],
    });

    console.log(`Pushed ${branchName} to origin.`);
  }

  /**
   * Generates rich PR Markdown body
   */
  public formatPrBody(
    bugReport: SlackBugReport,
    proposal: GeminiFixProposal,
    verification: VerificationResult,
    previewUrl: string
  ): string {
    const filesList = proposal.filesToModify
      .map(
        (f) =>
          `- \`${f.path}\` (${f.action}): ${f.explanation}`
      )
      .join("\n");

    const qaSteps = proposal.qaVerificationSteps
      .map((s, idx) => `${idx + 1}. ${s}`)
      .join("\n");

    return `## 🐛 Slack QA Bug Fix: ${proposal.bugSummary}

> Automated Pull Request generated by **Gemini Code Agent** with **Graphify Knowledge Graph** context.

---

### 📋 Original Bug Report
- **Reporter:** \`@${bugReport.reporter}\`
- **Channel:** \`${bugReport.channel || "qa-bugs"}\`
- **Reported At:** ${bugReport.reportedAt || new Date().toISOString()}
- **Description:**
> ${bugReport.text.replace(/\n/g, "\n> ")}

---

### 🔍 Root Cause Analysis
${proposal.rootCauseAnalysis}

---

### 🌐 Live Deploy Preview
QA and developers can test the fix immediately on the dedicated preview environment:
👉 **[Open Preview Deployment](${previewUrl})**

---

### 🛠️ Changes Made
${filesList}

---

### 🧪 Automated Quality Gates
- **Type Check:** ${verification.typeCheckPassed ? "✅ Passed" : "❌ Failed"}
- **Tests:** ${verification.testsPassed ? "✅ Passed" : "❌ Failed"}
- **Graphify Knowledge Graph:** ✅ Synchronized (\`graphify update .\`)

\`\`\`
${verification.output || verification.summary}
\`\`\`

---

### 👥 Sign-Off Checklist
- [ ] **QA Engineer (@${bugReport.reporter}):** Verify bug resolution on the [Preview Deployment](${previewUrl})
- [ ] **Developer Reviewer:** Review code diff against \`AGENTS.md\` standards and merge
`;
  }

  /**
   * Creates GitHub Pull Request via REST API
   */
  public async createPullRequest(
    branchName: string,
    baseBranch: string,
    bugReport: SlackBugReport,
    proposal: GeminiFixProposal,
    verification: VerificationResult,
    dryRun: boolean = false
  ): Promise<PullRequestResult> {
    const previewDomain =
      process.env.PREVIEW_BASE_DOMAIN || "preview.explys.dev";
    const previewUrl = `https://${branchName.replace(/\//g, "-")}.${previewDomain}`;
    const prTitle = `fix(qa): ${proposal.bugSummary}`;
    const prBody = this.formatPrBody(
      bugReport,
      proposal,
      verification,
      previewUrl
    );

    if (dryRun || !this.githubToken) {
      console.log(`[DRY RUN] Would create PR from ${branchName} into ${baseBranch}`);
      console.log(`Preview URL: ${previewUrl}`);
      console.log(`PR Title: ${prTitle}`);
      return {
        prNumber: 999,
        prUrl: `https://github.com/${this.repoOwner}/${this.repoName}/pull/999`,
        branchName,
        baseBranch,
        previewUrl,
        title: prTitle,
        body: prBody,
      };
    }

    const apiUrl = `https://api.github.com/repos/${this.repoOwner}/${this.repoName}/pulls`;
    const res = await fetch(apiUrl, {
      method: "POST",
      headers: {
        Authorization: `token ${this.githubToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: prTitle,
        head: branchName,
        base: baseBranch,
        body: prBody,
      }),
    });

    if (!res.ok) {
      const err = await res.text();
      throw new Error(`GitHub API create PR failed (${res.status}): ${err}`);
    }

    const data: any = await res.json();
    return {
      prNumber: data.number,
      prUrl: data.html_url,
      branchName,
      baseBranch,
      previewUrl,
      title: prTitle,
      body: prBody,
    };
  }
}
