export const ADMIN_TEST_ROWS = [
  {
    id: 1,
    title: "A1 Placement Test",
    type: "placement",
    level: "A1",
    questions: 20,
    duration: "15 min",
    attempts: 3456,
    avgScore: 72,
    passRate: 68,
    status: "active",
  },
  {
    id: 2,
    title: "Business Meeting Quiz",
    type: "video",
    level: "B1",
    questions: 10,
    duration: "5 min",
    attempts: 1234,
    avgScore: 84,
    passRate: 89,
    status: "active",
  },
  {
    id: 3,
    title: "Advanced Grammar Test",
    type: "practice",
    level: "C1",
    questions: 40,
    duration: "30 min",
    attempts: 654,
    avgScore: 65,
    passRate: 58,
    status: "draft",
  },
];

export const ADMIN_TEACHERS = [
  {
    id: 1,
    name: "Dr. Emily Watson",
    email: "emily.w@exply.dev",
    grades: ["Elementary", "Middle School"],
    topics: ["Grammar Basics", "Vocabulary", "Reading"],
    students: 234,
    rating: 4.9,
    lessonsCreated: 45,
    status: "active",
    joinedDate: "2023-06-15",
  },
  {
    id: 2,
    name: "James Rodriguez",
    email: "james.r@exply.dev",
    grades: ["High School", "Adults"],
    topics: ["Business English", "Presentations"],
    students: 189,
    rating: 4.8,
    lessonsCreated: 38,
    status: "active",
    joinedDate: "2023-08-20",
  },
  {
    id: 3,
    name: "Lisa Thompson",
    email: "lisa.t@exply.dev",
    grades: ["Middle School"],
    topics: ["Creative Writing", "Literature"],
    students: 145,
    rating: 4.8,
    lessonsCreated: 41,
    status: "pending",
    joinedDate: "2024-01-05",
  },
];

export const ADMIN_TOPIC_GROUPS = [
  {
    id: 1,
    name: "Business English",
    description: "Professional communication",
    emoji: "💼",
    topics: [
      { id: 101, name: "Business Meetings", videos: 12, tests: 5, level: "B1" },
      { id: 102, name: "Email Writing", videos: 8, tests: 4, level: "B1" },
    ],
  },
  {
    id: 2,
    name: "Travel & Tourism",
    description: "Phrases for travelers",
    emoji: "✈️",
    topics: [
      { id: 201, name: "At the Airport", videos: 8, tests: 3, level: "A2" },
      { id: 202, name: "Hotel Conversations", videos: 6, tests: 3, level: "A2" },
    ],
  },
];
